### PR TITLE
Make export busses with fuzzy cards pull from storages in order of priority

### LINKED ISSUE #706: Export Busses with Fuzzy Cards don't respect storage location priorities
### Your GTNH Discord Username

sayjanss.

### Mod Version

appliedenergistics2-rv3-beta-554-GTNH

### Bug Report

Title; export busses with fuzzy cards that are connected to a network with storage do not respect their priorities for where to extract from first; while they are applying fuzziness (hiding NBT Data). For example, cells that have different amounts of items on them that are extracted through a fuzzy card-export bus aren't chosen using the storage bus that has the lower priority; instead, it seems they are exported in alphabetical order or something similar. 

### Java Version

Java 21

### Mod List or GTNH Pack Version

GTNH Nightly 912

### Final Checklist

- [x] I have searched the issues and haven't found a similar issue.

### PR DESCRIPTION
**Pull request by Inphysible**
#706 

Added a function to NetworkInventoryHandler to retrieve a list of all items in an AE2 network in order of storage priority that matches a fuzzy filter. Then implemented this in PartExportBus with the use of `.getHandler()`, which returns a NetworkInventoryHandler object; otherwise, resolved implementations.

Closes #706

### CODE REVIEW

File: src/main/java/appeng/me/storage/NetworkInventoryHandler.java [hunk 1]
```diff
@@ -294,41 +352,13 @@ public IItemList<T> getAvailableItems(IItemList out, int iteration) {
 
         final List<IMEInventoryHandler<T>> priorityInventory = this.priorityInventory;
         final int size = priorityInventory.size();
-        for (int i = 0; i < size; i++) {
+        for (int i = size - 1; i >= 0; i--) {
```
Comment (lordIcocain) [inline src/main/java/appeng/me/storage/NetworkInventoryHandler.java:355]: ?

File: src/main/java/appeng/me/storage/NetworkInventoryHandler.java [hunk 2]
```diff
@@ -294,41 +352,13 @@ public IItemList<T> getAvailableItems(IItemList out, int iteration) {
...
+            final IMEInventoryHandler<T> inv = priorityInventory.get(i);
             out = priorityInventory.get(i).getAvailableItems(out, iteration);
         }
 
-        this.surface(this, Actionable.SIMULATE);
```
Comment (lordIcocain) [inline src/main/java/appeng/me/storage/NetworkInventoryHandler.java:301]: ?

File: src/main/java/appeng/api/storage/IMEInventory.java [hunk 3]
```diff
@@ -115,6 +118,22 @@ default StackType getAvailableItem(@Nonnull StackType request, int iteration) {
...
+     * @param out       the Collection the results will be written too
+     * @param fuzzyItem the AEItemStack that will be passed to findFuzzy as the filter
+     * @param fuzzyMode the FuzzyMode instance that will be passed to findFuzzy
+     * @param iteration numeric id for this iteration, use {@link appeng.util.IterationCounter#fetchNewId()} to avoid
+     *                  conflicts
+     * @return returns same list that was passed in, is passed out
+     */
+    default Collection<StackType> getSortedFuzzyItems(Collection<StackType> out, StackType fuzzyItem,
+            FuzzyMode fuzzyMode, int iteration) {
+        return this.getSortedFuzzyItems(out, fuzzyItem, fuzzyMode, iteration);
```
Comment (lordIcocain) [inline src/main/java/appeng/api/storage/IMEInventory.java:134]: return empty collection

File: src/main/java/appeng/me/storage/NetworkInventoryHandler.java [hunk 4]
```diff
@@ -294,41 +352,13 @@ public IItemList<T> getAvailableItems(IItemList out, int iteration) {
...
-
         return out;
-    }
-
-    @Override
-    public T getAvailableItem(@Nonnull T request, int iteration) {
```
Comment (lordIcocain) [inline src/main/java/appeng/me/storage/NetworkInventoryHandler.java:307]: could you please not move this function

**Comment by Inphysible** [comment]
all of those should be resolved now @lordIcocain, hopefully. I completely screwed up rebasing and merging changes before lol

File: src/main/java/appeng/api/storage/IMEInventory.java (hunk 3 above)
Comment (Inphysible) [reply src/main/java/appeng/api/storage/IMEInventory.java:134]: I wasn't sure what else to put there since I cannot define it like how I want to in that interface.

Comment (Inphysible) [reply src/main/java/appeng/api/storage/IMEInventory.java]: fixed.

**Comment by Dream-Master** [comment]
This pr break AE2FC

File: src/main/java/appeng/api/storage/IMEInventory.java [hunk 5]
```diff
@@ -75,7 +78,7 @@ default IItemList<StackType> getAvailableItems(IItemList<StackType> out) {
      *                  conflicts
      * @return returns same list that was passed in, is passed out
      */
-    default IItemList<StackType> getAvailableItems(IItemList<StackType> out, int iteration) {
```
Comment (lordIcocain) [inline src/main/java/appeng/api/storage/IMEInventory.java:78]: Dont do that

File: dependencies.gradle [hunk 6]
```diff
@@ -7,14 +7,14 @@ dependencies {
...
     compileOnly('com.github.GTNewHorizons:ForestryMC:4.10.7:dev') {transitive = false} // required to compile CraftingV2Tests.java now
     compileOnly('com.github.GTNewHorizons:ForgeMultipart:1.6.2:dev') {transitive = false}
+    compileOnly('com.github.GTNewHorizons:inventory-tweaks:1.7.1:api') {transitive = false}
+    compileOnly('com.github.GTNewHorizons:waila:1.8.4:dev') {transitive = false}
+    compileOnly('com.github.GTNewHorizons:BuildCraft:7.1.42:dev') {transitive = false}
     compileOnly('com.github.GTNewHorizons:GT5-Unofficial:5.09.51.275:dev') {transitive = false}
     compileOnly('com.github.GTNewHorizons:Jabba:1.5.4:dev') {transitive = false}
-    compileOnly('com.github.GTNewHorizons:inventory-tweaks:1.7.1:api') {transitive = false}
     compileOnly('com.github.GTNewHorizons:OpenComputers:1.11.13-GTNH:api') {transitive = false}
-    compileOnly('com.github.GTNewHorizons:waila:1.8.4:dev') {transitive = false}
```
Comment (serenibyss) [inline dependencies.gradle:17]: Could you avoid rearranging these?

File: dependencies.gradle [hunk 7]
```diff
@@ -42,6 +42,8 @@ dependencies {
     runtimeOnlyNonPublishable("com.github.GTNewHorizons:DuraDisplay:1.3.4:dev")
     runtimeOnlyNonPublishable('com.github.GTNewHorizons:Baubles:1.0.4:dev')
     runtimeOnlyNonPublishable('thaumcraft:Thaumcraft:1.7.10-4.2.3.5:dev')
+    //runtimeOnlyNonPublishable("com.github.GTNewHorizons:BloodMagic:1.7.8")  { transitive = false }
+    //runtimeOnlyNonPublishable("com.github.GTNewHorizons:BloodMagic:1.7.5")  { transitive = false }
```
Comment (serenibyss) [inline dependencies.gradle:46]: Could you remove these? We already have BloodMagic commented out lower down in the file if it is needed for local testing

File: src/main/java/appeng/api/storage/IMEInventory.java [hunk 8]
```diff
@@ -115,6 +118,22 @@ default StackType getAvailableItem(@Nonnull StackType request, int iteration) {
         return getAvailableItems((IItemList<StackType>) getChannel().createList(), iteration).findPrecise(request);
     }
 
+    /**
+     * Request a full report of all available items that match a fuzzy filter, in order of priority (descending order).
+     * Mostly relevant for extract-only inventories.
+     *
+     * @param out       the Collection the results will be written too
```
Comment (serenibyss) [inline src/main/java/appeng/api/storage/IMEInventory.java:125]:
```suggestion
     * @param out       the Collection the results will be written to
```

File: src/main/java/appeng/api/storage/IMEInventory.java [hunk 9]
```diff
@@ -115,6 +118,22 @@ default StackType getAvailableItem(@Nonnull StackType request, int iteration) {
...
+     * @param fuzzyItem the AEItemStack that will be passed to findFuzzy as the filter
+     * @param fuzzyMode the FuzzyMode instance that will be passed to findFuzzy
```
Comment (serenibyss) [inline src/main/java/appeng/api/storage/IMEInventory.java:127]: Could you do an `@link` for `findFuzzy()` here similar to `fetchNewId()` below?

File: src/main/java/appeng/api/storage/IMEInventory.java [hunk 10]
```diff
@@ -115,6 +118,22 @@ default StackType getAvailableItem(@Nonnull StackType request, int iteration) {
...
+     * @param iteration numeric id for this iteration, use {@link appeng.util.IterationCounter#fetchNewId()} to avoid
+     *                  conflicts
+     * @return returns same list that was passed in, is passed out
```
Comment (serenibyss) [inline src/main/java/appeng/api/storage/IMEInventory.java:130]: Is this return description always correct? It should be general to the expected behavior of any implementation, not just the default. i.e., `@return the priority list of available items` or something along those lines

File: src/main/java/appeng/me/storage/NetworkInventoryHandler.java [hunk 11]
```diff
@@ -341,6 +344,37 @@ private boolean diveIteration(final NetworkInventoryHandler<T> networkInventoryH
...
+
+        final List<IMEInventoryHandler<T>> priorityInventory = this.priorityInventory;
+        final int size = priorityInventory.size();
+        for (int i = size - 1; i >= 0; i--) {
+            final IMEInventoryHandler<T> invObject = priorityInventory.get(i);
+
+            if (!invObject.isAutoCraftingInventory()) {
+                final IItemList inv = invObject.getAvailableItems(
+                        invObject.getChannel().createList(),
+                        appeng.util.IterationCounter.fetchNewId());
```
Comment (serenibyss) [inline src/main/java/appeng/me/storage/NetworkInventoryHandler.java:365]: Could you import this rather than writing it fully qualified?

File: src/main/java/appeng/parts/automation/PartExportBus.java [hunk 12]
```diff
@@ -133,15 +137,28 @@ protected TickRateModulation doBusWork() {
...
-                                if (this.itemToSend <= 0) {
-                                    break;
-                                }
+
+                            /*
+                             * This actually returns a NetworkInventoryHandler object. The method .getSortedFuzzyItems()
+                             * used is the overriden one found in the .java file.
+                             */
+
+                            final Collection<IAEItemStack> fzlist = ((NetworkMonitor<IAEItemStack>) gridInv)
```
Comment (serenibyss) [inline src/main/java/appeng/parts/automation/PartExportBus.java:146]: I believe this is true now, but a sanity check `instanceof` on this would be nice for future changes in case this is not always true

File: src/main/java/appeng/parts/automation/PartExportBus.java [hunk 13]
```diff
@@ -133,15 +137,28 @@ protected TickRateModulation doBusWork() {
...
+                                    .getHandler().getSortedFuzzyItems(
+                                            new ArrayList<>(),
+                                            ais,
+                                            fzMode,
+                                            appeng.util.IterationCounter.fetchNewId());
+
+                            for (final IAEItemStack o : ImmutableList.copyOf(fzlist)) {
```
Comment (serenibyss) [inline src/main/java/appeng/parts/automation/PartExportBus.java:153]: Does this need to copy the list?

File: src/main/java/appeng/parts/automation/PartExportBus.java (hunk 12 above)
Comment (Inphysible) [reply src/main/java/appeng/parts/automation/PartExportBus.java:146]: how should i use instanceof here? Do you want `getSortedFuzzyItems()` to return a boolean as well or...?

File: src/main/java/appeng/me/storage/NetworkInventoryHandler.java (hunk 11 above)
Comment (Inphysible) [reply src/main/java/appeng/me/storage/NetworkInventoryHandler.java:365]: im not sure what you mean 😅

File: src/main/java/appeng/api/storage/IMEInventory.java (hunk 9 above)
Comment (Inphysible) [reply src/main/java/appeng/api/storage/IMEInventory.java]: Done

File: src/main/java/appeng/api/storage/IMEInventory.java (hunk 10 above)
Comment (Inphysible) [reply src/main/java/appeng/api/storage/IMEInventory.java]: no it isnt, what you described is the intended function lol, should be fixed now

File: src/main/java/appeng/me/storage/NetworkInventoryHandler.java (hunk 11 above)
Comment (serenibyss) [reply src/main/java/appeng/me/storage/NetworkInventoryHandler.java:365]: Import `IterationCounter` rather than typing out `appeng.util.IterationCounter.fetchNewId()`

File: src/main/java/appeng/api/storage/IMEInventory.java (hunk 8 above)
Comment (Inphysible) [reply src/main/java/appeng/api/storage/IMEInventory.java]: fixed.

File: src/main/java/appeng/parts/automation/PartExportBus.java (hunk 13 above)
Comment (Inphysible) [reply src/main/java/appeng/parts/automation/PartExportBus.java:153]: no. I'll commit an iterator of fzlist later with the other change to this file

File: src/main/java/appeng/parts/automation/PartExportBus.java (hunk 12 above)
Comment (serenibyss) [reply src/main/java/appeng/parts/automation/PartExportBus.java:146]: Something like:
```java
if (gridInv instanceof NetworkMonitor<IAEItemStack> monitor) {
    final Collection<IAEItemStack> fzlist = monitor.getHandler()
        .getSortedFuzzyItems(
            new ArrayList<>(),
            ais,
            fzMode,
            IterationCounter.fetchNewId());

    for (final IAEItemStack o : ImmutableList.copyOf(fzlist)) {
        this.pushItemIntoTarget(destination, energy, gridInv, o);
    }

    // ... whatever else is needed
}
```

File: dependencies.gradle (hunk 6 above)
Comment (Inphysible) [reply dependencies.gradle]: same as below

File: dependencies.gradle (hunk 7 above)
Comment (Inphysible) [reply dependencies.gradle:47]: i take that back, looking at these now

Comment (Inphysible) [reply dependencies.gradle]: fixed

File: dependencies.gradle (hunk 6 above)
Comment (Inphysible) [reply dependencies.gradle]: fixed

File: dependencies.gradle [hunk 14]
```diff
@@ -15,6 +15,7 @@ dependencies {
     compileOnly('com.github.GTNewHorizons:inventory-tweaks:1.7.1:api') {transitive = false}
     compileOnly('com.github.GTNewHorizons:OpenComputers:1.11.13-GTNH:api') {transitive = false}
     compileOnly('com.github.GTNewHorizons:waila:1.8.4:dev') {transitive = false}
+    compileOnly('com.github.GTNewHorizons:waila:1.8.4:dev') {transitive = false}
```
Comment (serenibyss) [inline dependencies.gradle:18]: Could you remove this duplicated dependency?

**Review by serenibyss — COMMENTED** [review]
Thanks for addressing the comments! Just one left

File: dependencies.gradle (hunk 14 above)
Comment (Inphysible) [reply dependencies.gradle:18]: yep

**Review by serenibyss — APPROVED** [review]
Thank you!
