### PR TITLE
Fix IO Port cell moving

### LINKED ISSUE #24238: ME IO Port not moving cell to output when storage is empty
### Your GTNH Discord Username

Jimbob5577

### Your Pack Version

2.8.3

### Your Server

Private

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

Cell should be moved to the output section as the ME inventory is empty however the cell is staying. This gitch breaks my UA setup. 

### The Reality

This gitch breaks my UA setup as the cell is staying in the ME IO port awaiting section even when the inventory attached is empty. 

me IO port with cell
Image

overview without cell info showing output is not full
Image

Me chest that is the only storage in the network
Image

UA setup 
(recipe in the half interface going into inteface. This is then attached to the ME chest with 4k cell inside. Then attached to the IO port. The cells output are then taken by an LV machine hull with 2 Iv conveyors into another ME IO port that input the recipe circuit via the interface / storage bus combo on the Blue net.)

Image

There is seemily another glitch which im not sure if is caused by this (cell staying when it shouldn't ) which is causing the recipes to overlap (2 recipes in 1 cell) the only thing i can think of is that the cell is still stuck in the IO port and the advanced blocking card doesnt see the items in the network anymore and so no longer blocks the input from the interface.

The Glitch happens intermitantly on some recipes and so will work sometimes and then at random it will occur. Not all recipes are effected

### Your Proposal

Please fix the glitch so that when the network is empty it always moves the cell to the output

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by Kogepan229**
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/24238

In FILL + MoveWhenEmpty mode, the IO Port effectively decided whether to move the cell based on whether the current tick transferred anything, instead of whether the network had actually become empty.
If the last tick drained exactly the remaining transfer budget, the move check was skipped, and on the next tick no transfer happened because the network was already empty, so the cell never moved to the output slot.

How to reproduce:
There are 257 items in the network, they will be moved to the cell and then the cell will move to output slot.
There are 256 items, the cell will not move to output slot.

### CODE REVIEW

File: src/main/java/appeng/tile/storage/TileIOPort.java [hunk 1]
```diff
@@ -470,26 +486,34 @@ private long transferContents(final IEnergySource energy, final IMEInventory src
...
                                 didStuff = true;
+                                if (availableBeforeExtract > possible) {
+                                    sourceHasRemainingItems = true;
+                                }
                             }
 
                             break;
                         }
+                    } else {
+                        sourceHasRemainingItems = true;
```
Comment (lc-1337) [inline src/main/java/appeng/tile/storage/TileIOPort.java:509]: what if items to move exactly == stacksize

File: src/main/java/appeng/tile/storage/TileIOPort.java [hunk 2]
```diff
@@ -344,44 +355,47 @@ public TickRateModulation tickingRequest(final IGridNode node, final int ticksSi
...
+                            didWork = transferResult.itemsLeftToMove != transferBudget;
                         }
                     }
 
                     // If work is done, check if the cell should be moved and try to move it to the output
                     // If the cell failed to move, queue moving the cell before doing any further work on it
-                    if (amountToMove > 0) {
-                        if (this.shouldMove(inv, amountToMove != maxMoved)) {
+                    if (amountToMove > 0
+                            || (operationMode == OperationMode.FILL && fullnessMode == FullnessMode.EMPTY)) {
```
Comment (lc-1337) [inline src/main/java/appeng/tile/storage/TileIOPort.java]: var = operationMode == OperationMode.FILL && fullnessMode == FullnessMode.EMPTY
also use that var for shouldMove parameter, i see no sense for 2 bool param and then use same if statment

File: src/main/java/appeng/tile/storage/TileIOPort.java (hunk 1 above)
Comment (Kogepan229) [reply src/main/java/appeng/tile/storage/TileIOPort.java:509]: `possible = itemsToMove - stack.getStackSize();`
The reason `possible` becomes 0 is because there are still items remaining in the source but none have been moved to the dest.

File: src/main/java/appeng/tile/storage/TileIOPort.java (hunk 2 above)
Comment (Kogepan229) [reply src/main/java/appeng/tile/storage/TileIOPort.java]: done

File: src/main/java/appeng/tile/storage/TileIOPort.java [hunk 3]
```diff
@@ -470,26 +492,35 @@ private long transferContents(final IEnergySource energy, final IMEInventory src
...
 
-        return itemsToMove;
+        return new TransferResult(itemsToMove, !sourceHasRemainingItems && !it.hasNext());
     }
 
-    private boolean shouldMove(final IMEInventory<?> inventory, final boolean didWork) {
-        final FullnessMode fm = (FullnessMode) this.manager.getSetting(Settings.FULLNESS_MODE);
-        final OperationMode om = (OperationMode) this.manager.getSetting(Settings.OPERATION_MODE);
+    private boolean shouldMove(final IMEInventory<?> inventory, final boolean sourceEmptyAfterTransfer,
+            final boolean didWork, final boolean moveOnEmptyWhileFilling, final OperationMode om,
```
Comment (lc-1337) [inline src/main/java/appeng/tile/storage/TileIOPort.java:519]: why keep "final OperationMode om, final FullnessMode fm" params ?

Comment (Kogepan229) [reply src/main/java/appeng/tile/storage/TileIOPort.java:519]: `matches` on line 526 uses those

Comment (lc-1337) [reply src/main/java/appeng/tile/storage/TileIOPort.java:519]: damn

**Review by lc-1337 — APPROVED** [review]

**Comment by jimbob5577** [comment]
Not sure if i can reopen this but i upadated to the latest daily with the change and this has created an unintentinal bug? me cells nolonger stay inside of the me io port if there is nothing to move e.g. an empty cell and an empty network when transfering data to the me cell and vis versa the cell will move to the output even if nothing has happend to the cell. it would probably be best if the orignal funtonality remained leaving the empty cell in the input if there is nothing to move into the cell.
