### PR TITLE
fix Pattern with recycling ingredient broken

### LINKED ISSUE #1064: Pattern with recycling item broken
### Your GTNH Discord Username

_No response_

### Mod Version

rv3-beta-817 - 826

### Bug Report

It works as follows:
There's a pattern with item a + item b = item c + item b
Put the pattern in an interface with normal blocking mode next to a chest set to pull item a and item b back into the system
Request 2 or more item c from terminal
Put 1 item c manually in the interface
Then the crafting stuck and doesn't push any more item to the chest

Before this, it works and pushes the item as it should

### Java Version

Java 8

### Mod List or GTNH Pack Version

Just ae2

### Final Checklist

- [x] I have searched the issues and haven't found a similar issue.

### PR DESCRIPTION
**Pull request by lc-1337**
Closes: https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/issues/1064

### CODE REVIEW

File: src/main/java/appeng/me/cluster/implementations/CraftingCPUCluster.java [hunk 1]
```diff
@@ -1966,6 +1966,16 @@ public void setSuspended(boolean suspended) {
         this.suspended = suspended;
     }
 
+    private boolean isFinalOutputNotIngredient(final IAEStack<?> finalOutput) {
+        if (this.tasks.isEmpty()) return true;
+        for (Entry<ICraftingPatternDetails, TaskProgress> e : this.tasks.entrySet()) {
+            for (final IAEStack<?> aes : e.getKey().getAEInputs()) {
```
Comment (Luca-Guettinger) [inline src/main/java/appeng/me/cluster/implementations/CraftingCPUCluster.java]: `getCondensedAEInputs()` would be a better fit here. `getAEInputs()` returns per-slot entries that can contain nulls (hence the null check), while `getCondensedAEInputs()` deduplicates by item type and has no null entries. Fewer iterations, no null guard needed.

File: src/main/java/appeng/me/cluster/implementations/CraftingCPUCluster.java [hunk 2]
```diff
@@ -1966,6 +1966,16 @@ public void setSuspended(boolean suspended) {
         this.suspended = suspended;
     }
 
+    private boolean isFinalOutputNotIngredient(final IAEStack<?> finalOutput) {
```
Comment (Luca-Guettinger) [inline src/main/java/appeng/me/cluster/implementations/CraftingCPUCluster.java]: This method is only called from the `finalOutput` inner class, which already accesses `tasks` directly (line 1986). Moving it into the inner class would keep the logic co-located.

**Review by Luca-Guettinger — COMMENTED** [review]
Clean fix, two minor suggestions.

**Comment by Kogepan229** [comment]
This fix has an issue.
For a pattern like a + b -> c + 2b, one returned b is needed for the next craft, but the extra b is still part of the requested final outputs and must be consumed from `finalOutput.outputs`.

With the current boolean check, all returned b stacks are routed as ingredients and none of them decrement the tracked final outputs.
This can leave finalOutput non-empty even after the actual craft is done, preventing completion. 
The logic needs to split by quantity, reserving only the amount still required by pending inputs and treating any surplus as final output.

**Comment by lc-1337** [comment]
@Kogepan229 check now

**Comment by Kogepan229** [comment]
@lc-1337 
There are several issues.
- isFinalOutput() is also called via the Actionable.SIMULATE path, but it was executing inventory.injectItems(aes, Actionable.MODULATE)
- It should have been subtracted from finalOutput.outputs as well, but it wasn't

It was difficult to explain these fixes properly, and I came up with some good changes while thinking about them, so I pushed them.
What do you think?

**Comment by lc-1337** [comment]
@Kogepan229 looks good

**Review by Kogepan229 — APPROVED** [review]
