### PR TITLE
Fix item insertion into parts on different sides

### LINKED ISSUE #1249: TileCableBus is accepting items from TileInterface
### Your GTNH Discord Username

_No response_

### Mod Version

master branch at this commit: 496b8b5846767ab04fa1eafa18ca509c55e3f084

### Bug Report

When TileInterface is processing a pattern and is trying to push items to nearby valid targets, connected cables (LayerIEnergyConnected_TileCableBus) count as valid targets and end up accepting the items instead of the intended inventory (input bus for example). In my case it was the cable above the TileInterface blocking it's access to the input bus.
I am not 100% sure this is a bug but it definitely seems not intended. I also have a fix ready but I don't think it addresses the underlying issue if it exists.

Example Setup:

Image

### Java Version

Java 8

### Mod List or GTNH Pack Version

I used the runClient task to test so I don't think a list is needed.

### Final Checklist

- [x] I have searched the issues and haven't found a similar issue.

### PR DESCRIPTION
**Pull request by Kogepan229**
Fixes https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/issues/1249

This method should return null when getAccessibleSlotsFromSide returns an empty array, but it was continuing so that IFluidHandler could still be handled.
As a result, AdaptorIInventory was returned, but it ignores getAccessibleSlotsFromSide, which allowed items to be inserted into parts on the wrong side.

Also, since TileCableBus does not have an inventory itself, this PR now returns null immediately when there is no part on that side.

### CODE REVIEW

File: src/main/java/appeng/util/InventoryAdaptor.java [hunk 1]
```diff
@@ -179,7 +183,7 @@ public static InventoryAdaptor getAdaptor(Object te, final ForgeDirection d,
             return new AdaptorFluidHandler(tank, d);
         }
 
-        if (invs && te instanceof IInventory i && i.getSizeInventory() > 0) {
+        if (invs && !(te instanceof ISidedInventory) && te instanceof IInventory i && i.getSizeInventory() > 0) {
```
Comment (lc-1337) [inline src/main/java/appeng/util/InventoryAdaptor.java]: Can you add else return null on 179 instead of this

Comment (Kogepan229) [reply src/main/java/appeng/util/InventoryAdaptor.java]: Done.
I hadn’t done that because it was meant to handle IFluidHandler, but I realized that’s already handled on line 157.

File: src/main/java/appeng/util/InventoryAdaptor.java [hunk 2]
```diff
@@ -172,13 +176,11 @@ public static InventoryAdaptor getAdaptor(Object te, final ForgeDirection d,
             
             if (invs && sided.getSizeInventory() > 0 && slots != null && slots.length > 0) {
                 return new AdaptorIInventory(new WrapperMCISidedInventory(sided, d));
+            } else {
+                return null;
             }
         }
 
-        if (tanks && te instanceof IFluidHandler tank && !(tank.getTankInfo(d) == null || !(tank.getTankInfo(d).length > 0))) {
```
Comment (lc-1337) [inline src/main/java/appeng/util/InventoryAdaptor.java:178]: Huh?

**Review by lc-1337 — APPROVED** [review]
